### ISSUE TITLE
Ensure compatibility with Nano Server

### ISSUE THREAD

**Issue by megamorf** [PowerShell/PSPrivateGallery#1]
First of all thanks a lot for providing this solution. I've been wanting to host an on-premise script gallery for a while now.

Has anyone tested this with Nano Server yet? Since Nano Server doesn't support MSI packages there'd need to be an alternative sql server express deployment method. The same goes for the amd64 setup.

Nano server would be my preferred OS for this project. Are there plans to repackage setups for the new Windows Server Application (WSA) format that is based on AppX?

Thanks in advance.

I'll gladly help out trying to make this project compatible with Nano Server :-)

**Comment by raghushantha** [comment]
@megamorf It would be great to port this solution to Nano.

Following need to be answered first:
1) [url rewrite on nano not available on nano yet](https://windowsserver.uservoice.com/forums/295068-nano-server/suggestions/13611888-support-of-url-rewrite-2-0-for-iis-on-nano-server)

2) SQL Server express on Nano - Either we can host the DB on a Core machine outside of Nano OR have the [SQL express running in a docker container on Nano](https://26thcentury.com/2016/01/03/dockerfile-to-create-sql-server-express-windows-container-image/)

3) Entity framework on Nano - don't think this is available on Nano

Also, why do we need to repackage as WSA? the MSI might be running some custom actions which cannot be done in WSA/APPX

**Comment by michaeltlombardi** [comment]
@raghushantha: Your second point should be addressed by #19, the others remain open.

I think the @megamorf's reasoning for WSA vs MSI is that MSIs won't run on Nano.
