### ISSUE TITLE
Cannot populate my instance of PS Gallery

### ISSUE THREAD

**Issue by i3kellyb** [PowerShell/PSPrivateGallery#10]
I'm getting an error when trying to populate my instance of the PS Gallery:
Write-NodeMOFFile : Invalid MOF definition for node 'localhost': Exception calling "ValidateInstanceText" with "1" argument(s): "Invalid embedded (reference) property value was found. The value object is of class type 
'ModuleSpecification', which is not 'ModuleSpecification[]' or its derived classes.
 At line:145, char:2
 Buffer:
ateGalleryPublish";
};^
insta
"
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:2275 char:21
- ...             Write-NodeMOFFile $Name $mofNode $Script:NodeInstanceAlia ...
-                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [Write-Error], InvalidOperationException
  - FullyQualifiedErrorId : InvalidMOFDefinition,Write-NodeMOFFile

Also, it won't allow me to sign in using my MSFT live account.

**Comment by michaeltlombardi** [comment]
Same error (Windows Server 2012 _non_ R2). Output of `$Error[0] | Format-List -Force`:

```
writeErrorStream      : True
Exception             : System.InvalidOperationException: Invalid MOF definition for node 'localhost': Exception
                        calling "ValidateInstanceText" with "1" argument(s): "Invalid embedded (reference) property
                        value was found. The value object is of class type 'ModuleSpecification', which is not
                        'ModuleSpecification[]' or its derived classes.
                         At line:145, char:2
                         Buffer:
                        ateGalleryPublish";
                        };^
                        insta
                        "
TargetObject          :
CategoryInfo          : InvalidOperation: (:) [Write-Error], InvalidOperationException
FullyQualifiedErrorId : InvalidMOFDefinition,Write-NodeMOFFile
ErrorDetails          : Invalid MOF definition for node 'localhost': Exception calling "ValidateInstanceText" with "1"
                        argument(s): "Invalid embedded (reference) property value was found. The value object is of
                        class type 'ModuleSpecification', which is not 'ModuleSpecification[]' or its derived classes.
                         At line:145, char:2
                         Buffer:
                        ateGalleryPublish";
                        };^
                        insta
                        "
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Write-NodeMOFFile, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfigur
                        ation\PSDesiredStateConfiguration.psm1: line 2920
                        at Configuration, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguratio
                        n\PSDesiredStateConfiguration.psm1: line 2275
                        at <ScriptBlock>, C:\PSPrivateGallery\Configuration\PSPrivateGalleryPublish.ps1: line 1
                        at <ScriptBlock>, C:\PSPrivateGallery\Configuration\PSPrivateGalleryPublish.ps1: line 73
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 0}
PSMessageDetails      :
```

**Comment by michaeltlombardi** [comment]
Same failure mode on 2012R2 but a successful deployment on 2016TP5.

@bgelens pointed out that TP5 has PowerShell v5.1 which includes some DSC updates. Need to update the docs or refactor the module for clarity since the PowerShell version deployed with WMF5 seems insufficient.

**Comment by i3kellyb** [comment]
Ok, I was able to get it running on 2016TP5.  I suppose if I had actually read the requirements of WMF 5.0, I would have gotten it to work the first time.

**Comment by michaeltlombardi** [comment]
In fairness, WMF5 is released for 2012R2 / etc. Even with it installed I was still getting all of those failure modes.
