### ISSUE TITLE
Cannot register/sign in to publish to my gallery

### ISSUE THREAD

**Issue by i3kellyb** [PowerShell/PSPrivateGallery#11]
I'm trying to publish modules to my private gallery and cannot.  When I try to get my NuGet API key by signing in (or registering), I get the following error: 'We're unable to complete your request'.  It appears that I do not have the correct URL for the Microsoft Live login.

**Comment by raghushantha** [comment]
@i3kellyb I have not tested the functionality with Live IDs with the [Gallery codebase](https://github.com/PowerShell/PSPrivateGallery/tree/master/Modules/PSGallery/GalleryContent)

Most likely the Gallery Codebase needs to be refreshed for this to work.
For now it works only with local accounts (that are stored in the SQL DB)

**Comment by i3kellyb** [comment]
@raghushantha How would I go about accessing the local accounts in the SQL db?

**Comment by raghushantha** [comment]
@i3kellyb Use either [SQLCMD](https://www.microsoft.com/en-us/download/details.aspx?id=52680) or [SQL Management Studio](https://msdn.microsoft.com/en-us/library/mt238290.aspx)

Example to connect to (LocalDB) instance:

You can refer to Users & Credentials table to look up local account info, including the APIKey:

1) Start a console in the context of the Database admin

```
runas /user:<machine>\GalleryAdmin cmd
```

2) Use SQLCMD to connect to the instance interactively:

```
C:\Program Files\Microsoft SQL Server\110\Tools\Binn>SQLCMD.EXE -S (LocalDB)\PSGallery
1> USE PSGallery
2> Select *from Users, Credentials
3> go
Changed database context to 'PSGallery'.
...
...
1>
```

**Comment by martin9700** [comment]
Has anyone ever gotten above to work?  Fresh install and I can't access the database, period.  I've runas GalleryAdmin with SSMS and SQLCMD and that instance just doesn't work.  What is it?

**Comment by raghushantha** [comment]
Closing as this is resolved.
