### ISSUE TITLE
Allow Any SQL Instance to Be Specified, Not Just LocalDB

### ISSUE THREAD

**Issue by ryanspletzer** [PowerShell/PSPrivateGallery#12]
That's fine for development / testing purposes but we'd like to use a real database hosted on a real instance of SQL Server in our environment, in which case we're rather not have to install SQL Express / LocalDB onto the Gallery server.

**Comment by michaeltlombardi** [comment]
Or the option to specify any SQL instance somewhere - Azure, on prem, AWS, whatever. Gallery shouldn't care what my SQL backend is, just that it exists and can be connected to.

**Comment by ryanspletzer** [comment]
Let me rename the issue.

**Comment by ryanspletzer** [comment]
For anyone following this issue... we were tinkering around internally but couldn't quite get the resources worked out enough to contribute up a commit to fix this.

What we're going to do in the meantime -- because we really don't want to run it in LocalDB -- is run [line 45](https://github.com/PowerShell/PSPrivateGallery/blob/master/Modules/PSGallery/DSCResources/PSGalleryDatabaseMigration/PSGalleryDatabaseMigration.psm1#L45) in PSGalleryDatabaseMigration, to manually generate the database in our preferred SQL instance, and then use the rest of the resources provided to set up the web server portion.

**Comment by ryanspletzer** [comment]
Myself and another developer worked on #19 which should allow you to specify a separate SQL server instance of your choice. Check out the forked repo if you want to use that in the meantime before something like this (hopefully) gets incorporated.

**Comment by ryanspletzer** [comment]
Swinging back to this from a long time ago. I think it's safe to close?
