### ISSUE TITLE
cant populate the Gallery

### ISSUE THREAD

**Issue by eosfor** [PowerShell/PSPrivateGallery#14]
PS C:\PSPrivateGallery\Configuration> C:\PSPrivateGallery\Configuration\PSPrivateGalleryPublish.ps1
Write-NodeMOFFile : Invalid MOF definition for node 'localhost': Exception calling "ValidateInstanceText" with "1" argument(s): "Invalid embedded (reference) property value was found. The value object is of class type 
'ModuleSpecification', which is not 'ModuleSpecification[]' or its derived classes.
 At line:155, char:2
 Buffer:
ateGalleryPublish";
};^
insta
"
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:2275 char:21
- ...             Write-NodeMOFFile $Name $mofNode $Script:NodeInstanceAlia ...
- ```
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ```
  - CategoryInfo          : InvalidOperation: (:) [Write-Error], InvalidOperationException
  - FullyQualifiedErrorId : InvalidMOFDefinition,Write-NodeMOFFile
  
  Directory: C:\PSPrivateGallery\Configuration\PSPrivateGalleryPublish

Mode                LastWriteTime         Length Name                                                                                                                                                                                

---

-a----         8/5/2016   7:50 AM           9604 localhost.mof.error  
Errors occurred while processing configuration 'PSPrivateGalleryPublish'.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:3705 char:5
-     throw $ErrorRecord
-     ~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (PSPrivateGalleryPublish:String) [], InvalidOperationException
  - FullyQualifiedErrorId : FailToProcessConfiguration

**Comment by raghushantha** [comment]
@eosfor Are you using WMF 5.0

Prerequisites:

Windows 10 / Windows OS containing WMF 5.0 RTM [https://www.microsoft.com/en-us/download/details.aspx?id=50395]

**Comment by michaeltlombardi** [comment]
@raghushantha: In our testing, it seemed to require WMF 5.1 or Windows Server 2016 TP5 - we were unable to get the private gallery to build on 2012R2 with WMF5.

**Comment by eosfor** [comment]
i'm using win2012 r2 with WMF5

**Comment by raghushantha** [comment]
Sorry about the confusion. Looks like the DSC Class based resource functionality along with composite resource required WMF 5.1 at a minimum. 

I have tested the code on WS2012R2+WMF5.1Preview and Server 2016 Preview. Please refer to [readme.md](https://github.com/PowerShell/PSPrivateGallery#prerequisites) to get WMF5.1.
