### ISSUE TITLE
Where i can fing ApiKey

### ISSUE THREAD

**Issue by eosfor** [PowerShell/PSPrivateGallery#15]
I'm trying to publish a module and I took GUID from PSPrivateGalleryEnvironment, but I cant. It fails with below error message

PS E:\Repo\wk-gss> Publish-Module -Path E:\Repo\wk-gss -NuGetApiKey '<SOME GUID>'
Publish-PSArtifactUtility : Failed to publish module 'wk-gss': 'Failed to process request. 'The specified API key is invalid.'. 
The remote server returned an error: (403) Forbidden..
'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:853 char:17
-                 Publish-PSArtifactUtility -PSModuleInfo $moduleInfo `
-                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [Write-Error], WriteErrorException
  - FullyQualifiedErrorId : FailedToPublishTheModule,Publish-PSArtifactUtility

**Comment by davidwallis** [comment]
I found it in the config file.

**Comment by raghushantha** [comment]
@eosfor 
https://github.com/PowerShell/PSPrivateGallery/blob/master/Configuration/PSPrivateGalleryPublishEnvironment.psd1

**Comment by eosfor** [comment]
And this does not work ). I took it from the mentioned file and it keeps saying that specified API key is invalid

**Comment by raghushantha** [comment]
@eosfor 
1) Is the LocalGallery registered? Use `Register-PSRepository`
2) Try using the `-Repository` parameter when using `Publish-Module` to target the local private Gallery

For additional debugging you can also open the local sql express db files in SQL management studio / use SQLCMD.

The API key must be in the Credentials table.

```
runas /user:<machine>\GalleryAdmin cmd
```

```
C:\Program Files\Microsoft SQL Server\110\Tools\Binn>SQLCMD.EXE -S (LocalDB)\PSGallery
1> USE PSGallery
2> Select *from Users, Credentials
3> go
Changed database context to 'PSGallery'.
...
...
1>
```

**Comment by raghushantha** [comment]
Closing as this is resolved
