### ISSUE TITLE
Allow for Setup of SSL/TLS in PSGalleryWebServer Composite DSC Resource

### ISSUE THREAD

**Issue by ryanspletzer** [PowerShell/PSPrivateGallery#18]
This resource doesn't provide any parameters to specify an SSL certificate to use to set up TLS for the gallery website in the nested xWebsite resource. That would very much be desired.

**Comment by michaeltlombardi** [comment]
Currently, there's an [issue](http://stackoverflow.com/questions/35296482/invalid-web-uri-error-on-register-psrepository) with registering remote repositories over HTTPS. Set up a private repo a few weeks back and tested when bound to SSL, same errors as linked above.

This is separate from your issue but something to be wary of.

**Comment by ryanspletzer** [comment]
So strangely enough, tried registering an https PS Private Gallery on WS 2012 R2 with WMF 5.0 -- no such issue. Maybe it was just a Windows 10 / WS 2016-specific thing for a little bit? ¯_(ツ)_/¯

**Comment by michaeltlombardi** [comment]
When I had tried it, it was on WMF5.0 RTM on W7. Interesting.
