### ISSUE TITLE
Create a chocolatey package

### ISSUE THREAD

**Issue by JasonMorgan** [PowerShell/PSPrivateGallery#2]
Heyo!  This is super awesome btw.  I'd like to be able to consume this easily and extend my existing Nuget DSC resource to create  a PSGallery feed.  It would be really handy if you could make a package similar to this one: https://chocolatey.org/packages/chocolatey.server.  

Regardless, I'd be happy to contribute and help as needed to get this going.  

The nuget DSC resource I'm referring to is located here: https://github.com/PowerShellOrg/NuGet

**Comment by raghushantha** [comment]
@JasonMorgan Thank you!

Feel free to contribute to the project.

Can you elaborate on the scenario for creating a OData feed like chocolatey.server?
