### ISSUE TITLE
SHA1 Password Hash Storage

### ISSUE THREAD

**Issue by ryanspletzer** [PowerShell/PSPrivateGallery#20]
Really? I would expect at least SHA-256 or even better a number of PBKDF2 iterations, with a salt...

https://github.com/PowerShell/PSPrivateGallery/blob/761326a8e6e639efe8751b243556a01b4bf34426/Modules/PSGallery/PSGallery.psm1#L336

I guess these are local accounts and not domain accounts, and the nature of what's being secured (PowerShell modules which you're trying to distribute) is not super sensitive, but still...

**Comment by raghushantha** [comment]
@ryanspletzer - Thanks for reporting the issue.

Fixed by https://github.com/PowerShell/PSPrivateGallery/commit/fb61ea16195f1487a41daf28b484f00c17f48d47

-Raghu
