### ISSUE TITLE
405 errors, and others..

### ISSUE THREAD

**Issue by davidwallis** [PowerShell/PSPrivateGallery#21]
So I can confirm on 2012r2 WMF 5.0 doesn't work and errors around the Invoke CimMethod.  (don't have the errors to hand any more! but they were pretty terminal)

5.1 gets further, but it appears that it doesn't install or enable WebDAV - (doesn't seem to throw errors)  which then gave me 405 method not allowed errors.. 

I'm now having issues with it configuring the source repo's

```
VERBOSE: [servername]:                            [[PackageManagementSource]SourceGallery] Repository details, Name
 = 'PSPrivateGallery', Location = 'http://servername:8080/api/v2/'; IsTrusted = 'True'; IsRegistered = 'True'.
The PSGallery repository has pre-defined locations. The 'Location, NewLocation or SourceLocation' parameter is not
allowed, try again after removing the 'Location, NewLocation or SourceLocation' parameter.
    + CategoryInfo          : InvalidArgument: (https://www.powershellgallery.com:) [], CimException
    + FullyQualifiedErrorId : ParameterIsNotAllowedWithPSGallery,Add-PackageSource,Microsoft.PowerShell.PackageManagem
   ent.Cmdlets.RegisterPackageSource
    + PSComputerName        : localhost

VERBOSE: [servername]: LCM:  [ End    Set      ]  [[PackageManagementSource]SourceGallery]  in 1.5780 seconds.
PowerShell DSC resource MSFT_PackageManagementSource  failed to execute Set-TargetResource functionality with error
message: Failed to register the package source PSGallery. Message:System.Exception: The PSGallery repository has
pre-defined locations. The 'Location, NewLocation or SourceLocation' parameter is not allowed, try again after
removing the 'Location, NewLocation or SourceLocation' parameter.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
```

Trying to re-run the install gives me a unable to insert duplicate row into the database around the user setup.

```
VERBOSE: [servername]:                            [[PSGalleryUser]PrivateGalleryUser] User 'GalleryUser' does not
exist in database 'PSGallery'
VERBOSE: [servername]:                            [[PSGalleryUser]PrivateGalleryUser] Adding user 'GalleryUser' to
database 'PSGallery'
VERBOSE: [servername]:                            [[PSGalleryUser]PrivateGalleryUser] 'Users' table in the database
 'PSGallery' on '(LocalDb)\PSGallery' instance is not populated. Populating the table...
Exception calling "ExecuteNonQuery" with "0" argument(s): "Cannot insert duplicate key row in object 'dbo.Users' with
unique index 'IX_UsersByUsername'. The duplicate key value is (GalleryUser).
The statement has been terminated."
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : SqlException,Set-TableData
    + PSComputerName        : localhost

VERBOSE: [servername]: LCM:  [ End    Set      ]  [[PSGalleryUser]PrivateGalleryUser]  in 0.6410 seconds.
The PowerShell DSC resource '[PSGalleryUser]PrivateGalleryUser' with SourceInfo
'C:\PSPrivateGallery\Configuration\PSPrivateGalleryPublish.ps1::35::9::PSGalleryUser' threw one or more
non-terminating errors while running the Set functionality. These errors are logged to the ETW channel called
Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost

VERBOSE: [servername]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost

VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 47.214 seconds
```

**Comment by davidwallis** [comment]
Just to add I have swapped back to windows 2012 r2 with GUI, after failing to get this working on 2016TP5 Core edition.

**Comment by davidwallis** [comment]
And then once I try and publish a module I get:

```
PS C:\temp> Publish-Module -Path .\MyModuleName -Repository PSPrivateGallery -NuGetApiKey c34d0782-b5ad-4b45-9165-a168b7f0436f
WARNING: This module 'C:\Users\!davidw\AppData\Local\Temp\225150623\MyModuleName\MyModuleName.psd1' has exported functions.
 As a best practice, include exported functions in the module manifest file(.psd1). You can run Update-ModuleManifest -FunctionsToExport to update
the manifest with ExportedFunctions field.
Publish-PSArtifactUtility : Failed to publish module 'MyModuleName': 'Cannot prompt for input in non-interactive mode.
'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1079 char:17
+                 Publish-PSArtifactUtility -PSModuleInfo $moduleInfo `
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : FailedToPublishTheModule,Publish-PSArtifactUtility

PS C:\temp>
```

I have ensured I have nuget downloaded: 

Invoke-WebRequest -Uri "http://go.microsoft.com/fwlink/?LinkID=690216&clcid=0x409" -OutFile "C:\ProgramData\Microsoft\Windows\PowerShell\PowerShellGet\NuGet.exe"

If I try an incorrect API key, I get the same error, rather than an incorrect API key.. 

Is there a way I can test this with NUGET?

**Comment by davidwallis** [comment]
HELP!!!

**Comment by michaeltlombardi** [comment]
Are you using PowerShell v5.0 or 5.1 on 2012R2? I _think_ it's broken on 5.0 based on my previous tests.

**Comment by davidwallis** [comment]
rebuilt the box as 2012 r2 with gui and WMF 5.1 - Tried 5.0 and that failed badly.. 
Rebuilt again after and did 5.1

**Comment by michaeltlombardi** [comment]
And that's the setup you're getting the API key errors for?

**Comment by davidwallis** [comment]
Yeah.  Don't suppose you documented the steps you used for a working
install or any prerequisites you installed prior

**Comment by michaeltlombardi** [comment]
I did, actually, [here](https://michaeltlombardi.github.io/PSPrivateGalleryWalkthrough/) - you can check the source repo for the configs/etc.

**Comment by davidwallis** [comment]
![image](https://cloud.githubusercontent.com/assets/13855486/18917985/4097160e-8591-11e6-9f3b-0c0b52cff02a.png)

Fresh build and slightly tweaked script to install results in the above:

```
[cmdletbinding()]
param (
    [string]$AdminPass,
    [string]$UserPass,
    [string]$ApiKey = (New-Guid | Select-Object -ExpandProperty Guid),
    [string]$EmailAddress = 'me@me.com',
    [string]$PrivateGalleryName = 'PSPrivateGallery'
)


dir -path "c:\pspg" -recurse |unblock-file

copy-item -path "c:\pspg\Modules\*" -Destination "$env:ProgramFiles\WindowsPowerShell\Modules" -recurse -force

Push-Location $PSScriptRoot
New-Object System.Management.Automation.PSCredential ('GalleryAdmin',(ConvertTo-SecureString $AdminPass -AsPlainText -Force)) | Export-Clixml -Path .\GalleryAdminCredFile.clixml
New-Object System.Management.Automation.PSCredential ('GalleryUser',(ConvertTo-SecureString $UserPass -AsPlainText -Force)) | Export-Clixml -Path .\GalleryUserCredFile.clixml

# Update the environment variables with those specified at build time.
$UpdatedGalleryEnvironment = Get-Content .\PSPrivateGalleryEnvironment.psd1 | ForEach-Object {
    $_.Replace('PSPrivateGallery',$PrivateGalleryName)
}
$UpdatedGalleryEnvironment | Out-File .\PSPrivateGalleryEnvironment.psd1

$UpdatedGalleryPublishEnvironment = Get-Content .\PSPrivateGalleryPublishEnvironment.psd1 | ForEach-Object {
    $Processing = $_.Replace('PSPrivateGallery',$PrivateGalleryName)
    $Processing = $Processing.Replace('First.Last@Domain.com',$EmailAddress)
    $Processing.Replace('ApiKeyGuid',$ApiKey)
}
$UpdatedGalleryPublishEnvironment | Out-File .\PSPrivateGalleryPublishEnvironment.psd1

& .\PSPrivateGallery.ps1
& .\PSprivateGalleryPublish.ps1
Pop-Location
```

**Comment by raghushantha** [comment]
Hi All.

The latest Master has all of the above issues fixed. I have verified on WS2012R2+WMF5.1 and Server 2016 Preview.

And @michaeltlombardi - excellent how-to on deploying PSPrivateGallery to Azure.
https://michaeltlombardi.github.io/PSPrivateGalleryWalkthrough/

-Raghu

**Comment by michaeltlombardi** [comment]
Glad to see this repo getting more love! :)

Started off writing a blog, ended up writing a walkthrough on our experience.

**Comment by davidwallis** [comment]
Look forward to trying this again :)

**Comment by davidwallis** [comment]
not resolved for me:
![image](https://cloud.githubusercontent.com/assets/13855486/19073194/918554c8-8a31-11e6-8263-92d8d7d8485b.png)

**Comment by davidwallis** [comment]
also if I try and publish with it in the above state I get:

![image](https://cloud.githubusercontent.com/assets/13855486/19073364/965bd20a-8a32-11e6-882c-b3511eb05b1b.png)

Last time I tracked this down to WebDAV not being installed..

**Comment by raghushantha** [comment]
@davidwallis3101 The first error is from `PackageManagementProviderResource`

I believe [v1.0.3](https://github.com/PowerShell/PSPrivateGallery/tree/master/Modules/PackageManagementProviderResource/1.0.3) of this resource has the fix. May I know the version of this DSC resource on your machine?

`Get-DscResource -Module PackageManagementProviderResource`

**Comment by davidwallis** [comment]
default build after installing wmf 5.1.. 

```
PS C:\WINDOWS\system32> Get-DscResource -Module PackageManagementProviderResource
WARNING: There are no modules present in the system with the given module specification.
PS C:\WINDOWS\system32>
```

after running:

```
$zipFile = 'c:\PSPrivateGallery-master.zip'
If (Test-Path $zipFile){ Remove-Item $zipFile }
Invoke-WebRequest -Uri "https://github.com/PowerShell/PSPrivateGallery/archive/master.zip" -OutFile $zipFile

Unblock-File $zipFile
Expand-Archive –Path $zipFile –DestinationPath "C:\" –Force

Rename-Item –Path "C:\PSPrivateGallery-master" –NewName "C:\PSPrivateGallery"

Copy-Item -path "C:\PSPrivateGallery\Modules\*" -Destination "$env:ProgramFiles\WindowsPowerShell\Modules" -recurse -force
```

I get the following

```
PS C:\WINDOWS\system32> Get-DscResource -Module PackageManagementProviderResource

ImplementedAs   Name                      ModuleName                     Version    Properties
-------------   ----                      ----------                     -------    ----------
PowerShell      NugetPackage              PackageManagementProviderRe... 1.0.3      {DestinationPath, Name, DependsO.
PowerShell      PackageManagement         PackageManagementProviderRe... 1.0.3      {Name, AdditionalParameters, Dep.
PowerShell      PackageManagementSource   PackageManagementProviderRe... 1.0.3      {Name, ProviderName, SourceUri, .
PowerShell      PSModule                  PackageManagementProviderRe... 1.0.3      {Name, DependsOn, Ensure, Instal.


PS C:\WINDOWS\system32>
```

so lets try an install by running:

```
Cd "C:\PSPrivateGallery\Configuration"

New-Object System.Management.Automation.PSCredential ('GalleryAdmin',(ConvertTo-SecureString "APassword" -AsPlainText -Force)) | Export-Clixml -Path .\GalleryAdminCredFile.clixml
New-Object System.Management.Automation.PSCredential ('GalleryUser',(ConvertTo-SecureString "APassword" -AsPlainText -Force)) | Export-Clixml -Path .\GalleryUserCredFile.clixml

.\PSPrivateGallery.ps1

.\PSPrivateGalleryPublish.ps1
```

get the following errors:

`VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' =
SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' =
root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer SERVER with user sid
S-1-5-21-196282956-19940018-89367796-25974.
VERBOSE: [SERVER]: LCM:  [ Start  Set      ]
VERBOSE: [SERVER]: LCM:  [ Start  Resource ]  [[PackageManagementSource]SourceGallery]
VERBOSE: [SERVER]: LCM:  [ Start  Test     ]  [[PackageManagementSource]SourceGallery]
VERBOSE: [SERVER]:                            [[PackageManagementSource]SourceGallery] Begin invoking
Get-packageSource PSGallery
VERBOSE: [SERVER]:                            [[PackageManagementSource]SourceGallery] Repository details, Name
 = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2/'; IsTrusted = 'False'; IsRegistered = 'True'.
VERBOSE: [SERVER]:                            [[PackageManagementSource]SourceGallery] Repository details, Name
 = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2/'; IsTrusted = 'False'; IsRegistered = 'True'.
VERBOSE: [SERVER]:                            [[PackageManagementSource]SourceGallery] Package source
'PSGallery' not found
VERBOSE: [SERVER]:                            [[PackageManagementSource]SourceGallery] Resource PSGallery is
not in the desired state. Required Ensure is Present and actual Ensure is Absent
VERBOSE: [SERVER]: LCM:  [ End    Test     ]  [[PackageManagementSource]SourceGallery]  in 10.4530 seconds.
VERBOSE: [SERVER]: LCM:  [ Start  Set      ]  [[PackageManagementSource]SourceGallery]
WARNING: [SERVER]:                            [[PackageManagementSource]SourceGallery] Begin registering
'PSGallery' to source location 'https://www.powershellgallery.com' with 'Trusted' policy"
VERBOSE: [SERVER]:                            [[PackageManagementSource]SourceGallery] Begin invoking
Register-Packagesource PSGallery
VERBOSE: [SERVER]:                            [[PackageManagementSource]SourceGallery] Repository details, Name
 = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2/'; IsTrusted = 'False'; IsRegistered = 'True'.
VERBOSE: [SERVER]:                            [[PackageManagementSource]SourceGallery] Successfully
unregistered the repository 'PSGallery'.
VERBOSE: [SERVER]:                            [[PackageManagementSource]SourceGallery] Repository details, Name
 = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2/'; IsTrusted = 'True'; IsRegistered = 'True'.
VERBOSE: [SERVER]:                            [[PackageManagementSource]SourceGallery] Successfully registered
the package source PSGallery
VERBOSE: [SERVER]: LCM:  [ End    Set      ]  [[PackageManagementSource]SourceGallery]  in 2.2340 seconds.
VERBOSE: [SERVER]: LCM:  [ End    Resource ]  [[PackageManagementSource]SourceGallery]
VERBOSE: [SERVER]: LCM:  [ Start  Resource ]  [[PackageManagementSource]PrivateGallery]
VERBOSE: [SERVER]: LCM:  [ Start  Test     ]  [[PackageManagementSource]PrivateGallery]
VERBOSE: [SERVER]:                            [[PackageManagementSource]PrivateGallery] Begin invoking
Get-packageSource PSPrivateGallery
VERBOSE: [SERVER]:                            [[PackageManagementSource]PrivateGallery] Package source
'PSPrivateGallery' not found
VERBOSE: [SERVER]:                            [[PackageManagementSource]PrivateGallery] Resource
PSPrivateGallery is not in the desired state. Required Ensure is Present and actual Ensure is Absent
VERBOSE: [SERVER]: LCM:  [ End    Test     ]  [[PackageManagementSource]PrivateGallery]  in 0.7650 seconds.
VERBOSE: [SERVER]: LCM:  [ Start  Set      ]  [[PackageManagementSource]PrivateGallery]
WARNING: [SERVER]:                            [[PackageManagementSource]PrivateGallery] Begin registering
'PSPrivateGallery' to source location 'http://localhost:8080' with 'Trusted' policy"
VERBOSE: [SERVER]:                            [[PackageManagementSource]PrivateGallery] Begin invoking
Register-Packagesource PSPrivateGallery
VERBOSE: [SERVER]:                            [[PackageManagementSource]PrivateGallery] Repository details,
Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2/'; IsTrusted = 'True'; IsRegistered = 'True'.
The specified Uri 'http://localhost:8080' for parameter 'Location' is an invalid Web Uri. Please ensure that it meets
the Web Uri requirements.
    + CategoryInfo          : InvalidArgument: (http://localhost:8080:) [], CimException
    + FullyQualifiedErrorId : InvalidWebUri,Add-PackageSource,Microsoft.PowerShell.PackageManagement.Cmdlets.RegisterP
   ackageSource
    + PSComputerName        : localhost

VERBOSE: [SERVER]: LCM:  [ End    Set      ]  [[PackageManagementSource]PrivateGallery]  in 31.8600 seconds.
PowerShell DSC resource MSFT_PackageManagementSource  failed to execute Set-TargetResource functionality with error
message: Failed to register the package source PSPrivateGallery. Message:System.Exception: The specified Uri
'http://localhost:8080' for parameter 'Location' is an invalid Web Uri. Please ensure that it meets the Web Uri
requirements.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

VERBOSE: [SERVER]: LCM:  [ Start  Resource ]  [[PSGalleryUser]PrivateGalleryUser]
VERBOSE: [SERVER]: LCM:  [ Start  Test     ]  [[PSGalleryUser]PrivateGalleryUser]
VERBOSE: [SERVER]:                            [[PSGalleryUser]PrivateGalleryUser] Get UserSettings for user
'GalleryUser'
VERBOSE: [SERVER]:                            [[PSGalleryUser]PrivateGalleryUser] User 'GalleryUser' does not
exist in database 'PSGallery'
VERBOSE: [SERVER]:                            [[PSGalleryUser]PrivateGalleryUser] User information does not
exist in database 'PSGallery' and Ensure is set to 'Present'
VERBOSE: [SERVER]: LCM:  [ End    Test     ]  [[PSGalleryUser]PrivateGalleryUser]  in 0.7190 seconds.
VERBOSE: [SERVER]: LCM:  [ Start  Set      ]  [[PSGalleryUser]PrivateGalleryUser]
VERBOSE: [SERVER]:                            [[PSGalleryUser]PrivateGalleryUser] Get UserSettings for user
'GalleryUser'
VERBOSE: [SERVER]:                            [[PSGalleryUser]PrivateGalleryUser] User 'GalleryUser' does not
exist in database 'PSGallery'
VERBOSE: [SERVER]:                            [[PSGalleryUser]PrivateGalleryUser] Adding user 'GalleryUser' to
database 'PSGallery'
VERBOSE: [SERVER]:                            [[PSGalleryUser]PrivateGalleryUser] 'Users' table in the database
 'PSGallery' on '(LocalDB)\PSGallery' instance is not populated. Populating the table...
VERBOSE: [SERVER]:                            [[PSGalleryUser]PrivateGalleryUser] Setting connection string
VERBOSE: [SERVER]:                            [[PSGalleryUser]PrivateGalleryUser] The 'Users' table in the
database 'PSGallery' on '(LocalDB)\PSGallery' instance has been populated.
VERBOSE: [SERVER]:                            [[PSGalleryUser]PrivateGalleryUser] Setting connection string
VERBOSE: [SERVER]:                            [[PSGalleryUser]PrivateGalleryUser] 'Credentials' table in the
database 'PSGallery' on '(LocalDB)\PSGallery' instance is not populated. Populating the table...
VERBOSE: [SERVER]:                            [[PSGalleryUser]PrivateGalleryUser] Setting connection string
VERBOSE: [SERVER]:                            [[PSGalleryUser]PrivateGalleryUser] The 'Credentials' table in
the database 'PSGallery' on '(LocalDB)\PSGallery' instance has been populated.
VERBOSE: [SERVER]: LCM:  [ End    Set      ]  [[PSGalleryUser]PrivateGalleryUser]  in 0.3280 seconds.
VERBOSE: [SERVER]: LCM:  [ End    Resource ]  [[PSGalleryUser]PrivateGalleryUser]
VERBOSE: [SERVER]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost

VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 48.255 seconds

PS C:\PSPrivateGallery\Configuration>`

**Comment by davidwallis** [comment]
fixed it and created a pull request.

**Comment by raghushantha** [comment]
@davidwallis3101 I will close this issue as resolved.

Please let me know otherwise
