### ISSUE TITLE
Key not valid for use in specific state

### ISSUE THREAD

**Issue by midacts** [PowerShell/PSPrivateGallery#23]
Server 2012 R2 - fresh install
I have followed your instruction (.NET 4.6 and WMF is installed as well).

When I run ~\Configuration\PSPrivateGallery.ps1, it fails with this:

VERBOSE: Performing the operation "Start-DscConfiguration: SendMetaConfigurationApply" on target
"MSFT_DSCLocalConfigurationManager".
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' =
SendMetaConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' =
root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer SERVERNAME with user sid
S-1-1-1
VERBOSE: [SERVERNAME]: LCM:  [ Start  Set      ]
VERBOSE: [SERVERNAME]: LCM:  [ Start  Resource ]  [MSFT_DSCMetaConfiguration]
VERBOSE: [SERVERNAME]: LCM:  [ Start  Set      ]  [MSFT_DSCMetaConfiguration]
VERBOSE: [SERVERNAME]: LCM:  [ End    Set      ]  [MSFT_DSCMetaConfiguration]  in 0.0150 seconds.
VERBOSE: [SERVERNAME]: LCM:  [ End    Resource ]  [MSFT_DSCMetaConfiguration]
VERBOSE: [SERVERNAME]: LCM:  [ End    Set      ]
VERBOSE: [SERVERNAME]: LCM:  [ End    Set      ]    in  0.0940 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Set-DscLocalConfigurationManager finished in 0.123 seconds.
PSDesiredStateConfiguration\Node : Key not valid for use in specified state.
At C:\PSPrivateGallery\Configuration\PSPrivateGallery.ps1:20 char:5
-     Node $AllNodes.Where{$_.Role -eq 'WebServer'}.Nodename
-     ~~~~
  - CategoryInfo          : NotSpecified: (:) [PSDesiredStateConfiguration\node], CryptographicException
  - FullyQualifiedErrorId : System.Security.Cryptography.CryptographicException,PSDesiredStateConfiguration\node

Compilation errors occurred while processing configuration 'PSPrivateGallery'. Please review the errors reported in
error stream and modify your configuration code appropriately.
At
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:3917
char:5
-     throw $ErrorRecord
-     ~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (PSPrivateGallery:String) [], InvalidOperationException
  - FullyQualifiedErrorId : FailToProcessConfiguration

**Comment by raghushantha** [comment]
@Midacts It is possible that the apppool identity (GalleryAdmin) user has no permissions to access the Cert Store on the machine.

Is there anything interesting in DSC ETW logs?
Event Viewer -> Applications and Services Logs -> Microsoft/Windows/Desired State Configuration.

Look at Operational/Analytic/Debug logs

**Comment by midacts** [comment]
That fixed it (The GallaryAdmin/User accounts)!

I just made a dummy username and password. I can use an actual one. Is it possible to remove those XML files that store the creds afterwords? (I'd rather not have my creds sitting in a place that people can get to). 

Can I use a different user besides GallerAdmins/User? It looks like i might be able to use a domain account instead of GalleryAdmin? It's referenced in the PSPrivateGallery.ps1 file. (I am mainly just wondering if it has to stay in the 'Administrators' group of the server permanently).

Thanks for providing the full path to the event logs. There are only info logs. Nothing out of the ordinary.

**Comment by raghushantha** [comment]
Yes. You can use a non-local Credential, however the identity you are using must have the rights to perform operations such as create an IIS endpoint, create a DB so on - on the machine.

Just supply the domain creds here (instead of reading from the Config data file):
https://github.com/PowerShell/PSPrivateGallery/blob/master/Configuration/PSPrivateGallery.ps1#L23

Also,  PowerShell uses Windows Data Protection API [DPAPI](https://msdn.microsoft.com/en-us/library/ms995355.aspx) to encrypt/decrypt your strings. So the serialized contents can be considered secure.

**Comment by midacts** [comment]
That makes sense. Thanks for your help on this.

Once it is deployed, is there any easy way to publish modules to the gallery?
When i click the "Publish Module" tab and click "Sign in with Microsoft account" it goes to a "We're unable to complete your request. Microsoft account is experiencing technical problems. Please try again later." Maybe it is something on the login.live.com side.

**Comment by OneGetTeam** [comment]
@Midacts The gallery front end code is not up to date with the production version https://www.powershellgallery.com. Hence you will be unable to publish using the website.

Using `Publish-Module` cmdlet is feasible. Use the API Key you supplied in the config data.

**Comment by midacts** [comment]
I got the APIkey from the C:\PSPrivateGallery\onfiguration\PSPrivateGalleryPublishEnvironment.psd1 file. Is that correct or how would I get the API key?
Here is what I run: 

```
PS C:\> Import-Module <MODULENAME>
PS C:\> $cred = Import-Clixml C:\PSPrivateGallery\Configuration\GalleryAdminCredFile.clixml
PS C:\> Publish-Module -Name <MODULENAME> -NuGetApiKey c34d0782-b5ad-4b45-9165-a168b7f0436f -Repository <REPONAME> -Credential $cred -Force
```

When I run Publish-Module I get this error:
Publish-PSArtifactUtility : Failed to publish module '<MODULENAME>': 'Failed to process request. 'The specified API key is
invalid or does not have permission to access the specified package.'.
The remote server returned an error: (403) Forbidden..
'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1079 char:17
-                 Publish-PSArtifactUtility -PSModuleInfo $moduleInfo `
-                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [Write-Error], WriteErrorException
  - FullyQualifiedErrorId : FailedToPublishTheModule,Publish-PSArtifactUtility

**Comment by raghushantha** [comment]
@Midacts Checkout my response to a similar question.

You can look up the API Key in the Credentials table (in (LocalDB)\PSGallery database) 

https://github.com/PowerShell/PSPrivateGallery/issues/15

**Comment by raghushantha** [comment]
Please reactivate if you have questions
