### ISSUE TITLE
Loadbalancing / resilience

### ISSUE THREAD

**Issue by davidwallis** [PowerShell/PSPrivateGallery#24]
I noticed a commit has been done for an external sql box.. is there scope for fronting the gallery with a loadbalancer for resilience?

**Comment by raghushantha** [comment]
I think the primary scenario was to host the webserver as in a SaaS environment let the front end scale up based on demand. The backend would be SQL Azure or equivalent. However this applies to the cloud.

The loadbalancer would be a on-prem equivalent - which is possible.
