### ISSUE TITLE
Readme Order

### ISSUE THREAD

**Issue by JulienFloris** [PowerShell/PSPrivateGallery#27]
The order in the Readme will cause an error on step:
`Start-DscConfiguration -Path .\PSPrivateGalleryPublish -Wait -Force -Verbose`

To fix this move the cmdlet up:
`New-NetFirewallRule -Name PSGallery -DisplayName "PSGallery" -Description "Allow access to the PSGallery" -Protocol TCP -RemoteAddress Any -LocalPort 8080 -Action Allow -enabled True`

**Comment by davidwallis** [comment]
The line Start-DscConfiguration -Path .\PSPrivateGalleryPublish -Wait -Force -Verbose isnt in the readme, but New-NetFirewallRule does want moving before trying to find a module so have created a PR for that.

**Comment by raghushantha** [comment]
@JulienFloris Thanks for pointing to the issue.
@davidwallis3101 Thanks for the PR. Accepted!
