### ISSUE TITLE
This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms. 

### ISSUE THREAD

**Issue by jmpetty21** [PowerShell/PSPrivateGallery#29]
I am receiving this error when i deploy this to my server 2012R2 server. 

This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.

**Comment by raghushantha** [comment]
@jmpetty21 I have not seen this issue.

Please refer to https://social.msdn.microsoft.com/Forums/vstudio/en-US/7a62c936-b3cc-4493-a3cd-cc5fd18b6b2a/fips-validated-cryptographic-algorithms?forum=clr for the solution.
