### ISSUE TITLE
Add ability for Scripts to be shared like on PowerShellGallery.com

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PSPrivateGallery#3]
Brings some feature parity between a Private Gallery & the PowerShellGallery

@raghushantha - tagging you as mentioned on tweet by @JKeithB

**Comment by raghushantha** [comment]
@kilasuit Definitely! The goal is to be in parity with PowerShellGallery.com

Ideally we must use a single Gallery codebase.

**Comment by kilasuit** [comment]
@raghushantha - Do you have any timeframes in mind for when this would be available at all?
