### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by jmpetty21** [PowerShell/PSPrivateGallery#30]
I am unable to log in or to publish to my private gallery (just deployed). The only option is to to sing in with a Microsoft account

**Comment by constantinhager** [comment]
I'm facing the same issue. Fresh install. The same Problem

**Comment by raghushantha** [comment]
@jmpetty21 @constantinhager Please refer to https://github.com/PowerShell/PSPrivateGallery/issues/11

The Gallery code base is dated  (compared to www.powershellgallery.com) and not been tested with Microsoft Accounts.

Only localaccounts (stored in DB) works.

**Comment by michaeltlombardi** [comment]
@raghushantha: Is there any expectation that the PSPrivateGallery code will sync back up with the public gallery, or is this project considered non-active-development at this time?

**Comment by raghushantha** [comment]
@michaeltlombardi  Please refer to issue https://github.com/PowerShell/PSPrivateGallery/issues/33
