### ISSUE TITLE
No modules showing

### ISSUE THREAD

**Issue by davidwallis** [PowerShell/PSPrivateGallery#31]
My gallery was working fine, it now is displaying no modules.. 

Any suggestions for troubleshooting? 

Thanks

**Comment by davidwallis** [comment]
further investigation reveals the web page shows nothing..  specify the module name in the url and it shows the module.

```powershell
Find-Module -Repository PSPrivateGallery
```
returns nothing.. 

```powershell
Find-Module PSake -Repository PSPrivateGallery
```
returns the psake module.. 

![capture](https://cloud.githubusercontent.com/assets/13855486/24109062/77b25cc4-0d87-11e7-84c2-ff1909eccb28.JPG)

**Comment by davidwallis** [comment]
And now it seems to be working ok this morning - and I haven't changed anything!

**Comment by raghushantha** [comment]
@davidwallis3101 Did you check IIS logs when modules were not being returned, might be an issue with the front end?

WebAppPool / WebSite might have restarted between resulting in normal operations
