### ISSUE TITLE
Unable to delete modules

### ISSUE THREAD

**Issue by matthitchcock** [PowerShell/PSPrivateGallery#32]
Logging an issue following discussion with Angel Calvo. My customer is trying the PS Private Gallery and is unable to delete modules after they are published.

I understand a cmdlet is missing (it's referenced as a To Do in the code), we have tried removing all references from the database but the modules still persist.

In the absence of a cmdlet can we have some guidance for in-publishing modules through the database directly?

Thanks

**Comment by raghushantha** [comment]
@matthitchcock @michaeltlombardi

It looks like changes are required to the DB as well as to web front end to remove items from the Gallery. Here are the steps based on my investigation - on Windows Server 2016:

[Refer to attached PSGallery Database diagram]
[PSGalleryDBDiagram.pdf](https://github.com/PowerShell/PSPrivateGallery/files/985591/PSGalleryDBDiagram.pdf)


[DB Step]
1) Using [SQL Server Management studio](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms) (or equivalent), delete the module entry in following tables:

```
--- [Key] points to the Module you need to remove
---[PackageRegistrationKey] is the corresponding value to [Key] in certain tables
delete from dbo.PackageAuthors where [Key]=5
delete from dbo.packages where [Key]=5
delete from dbo.PackageRegistrationOwners where [PackageRegistrationKey]=3
delete from dbo.PackageRegistrations where [Key]=3

-- check following tables to make sure required module entry is removed
select * from dbo.PackageAuthors
select * from dbo.packages
select * from dbo.PackageDependencies
select * from dbo.PackageFrameworks
select * from dbo.PackageRegistrationOwners
select * from dbo.PackageRegistrations
select * from dbo.PackageOwnerRequests

```

[Web Front End Step]
2) Clean App_Data cached/lucene indexed locations in Website path ($env:SystemDrive:\PSGallery by default)

```
# Stop Gallery WebAppPool
Get-IISAppPool -Name PSGalleryAppPool | Stop-WebAppPool

# Stop Gallery WebSite
Get-WebSite -Name PSGallery | Stop-Website

# Removed cached data
Del C:\PSGallery\App_Data\Files\packages\<PackageToBeRemoved>
Del C:\PSGallery\App_Data\Lucene\*.*

# Start Gallery WebAppPool
Get-IISAppPool -Name PSGalleryAppPool | Start-WebAppPool

# Start Gallery WebSite
Get-WebSite -Name PSGallery | Start-Website
```

I wanted to suggest a tool such as [galops](https://github.com/NuGet/NuGetGallery/issues/3309), to perform db management operations, but looks like its been removed from [NugetGallery Operations](https://github.com/NuGet/NuGetGallery/issues/3309), and the version of PSGallery shipped with this project does not contain galops.exe.

SQLStudio gives a better understanding of the DB Schema.

Let me know if this works.

**Comment by michaeltlombardi** [comment]
Should the Gallery have its own management module? These steps would get pretty tedious, might make sense for their to be a `Remove-PublishedModule` function or something.
