### ISSUE TITLE
Release plan

### ISSUE THREAD

**Issue by Glober777** [PowerShell/PSPrivateGallery#33]
Dear PSPrivateGallery team, is there any target date to have the project released as currently it seems that the project has stalled? I'd really like to have it deployed within my network.

**Comment by raghushantha** [comment]
Hi @Glober777 Currently I have no plans to sync the codebase to the [public version of the gallery](https://www.powershellgallery.com), do to limited resources on my part.

Also, the public gallery codebase has diverged significantly from the version here and would require a complete rewrite of the modules and introduction of new modules.

Will share with the community if I have any new updates.

Please consider the [latest release](https://github.com/PowerShell/PSPrivateGallery/releases) as the most current
