### ISSUE TITLE
Problem finding psgallerywebserver dscresource when  executing PSPrivateGallery.ps1

### ISSUE THREAD

**Issue by powersheller** [PowerShell/PSPrivateGallery#34]
I'm trying to use psprivategallery to create an internal powershell repository, but I keep getting this error. 
VERBOSE: Performing the operation "Start-DscConfiguration: SendMetaConfigurationApply" on target "MSFT_DSCLocalConfigurationManager".
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendMetaConfigurationApply,'className' =
MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer XX123456 with user sid S-1-5-21-4278529026-3823030349-3524473939-155576.
VERBOSE: [SE131346]: LCM:  [ Start  Set      ]
VERBOSE: [SE131346]: LCM:  [ Start  Resource ]  [MSFT_DSCMetaConfiguration]
VERBOSE: [SE131346]: LCM:  [ Start  Set      ]  [MSFT_DSCMetaConfiguration]
VERBOSE: [SE131346]: LCM:  [ End    Set      ]  [MSFT_DSCMetaConfiguration]  in 0.0160 seconds.
VERBOSE: [SE131346]: LCM:  [ End    Resource ]  [MSFT_DSCMetaConfiguration]
VERBOSE: [SE131346]: LCM:  [ End    Set      ]
VERBOSE: [SE131346]: LCM:  [ End    Set      ]    in  0.0940 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Set-DscLocalConfigurationManager finished in 0.172 seconds.
PSDesiredStateConfiguration\Node : The module 'PSGalleryWebServer' could not be loaded. For more information, run 'Import-Module PSGalleryWebServer'.
At F:\psprivategallery\configuration\PSPrivateGallery.ps1:20 char:5
+     Node $AllNodes.Where{$_.Role -eq 'WebServer'}.Nodename
+     ~~~~
    + CategoryInfo          : ObjectNotFound: (PSGalleryWebServer\PSGalleryWebServer:String) [PSDesiredStateConfiguration\node], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CouldNotAutoLoadModule,PSDesiredStateConfiguration\node

PS F:\psprivategallery\configuration> get-module *gallery*

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0.0.1    PSGallery                           {Assert, Get-ModuleSpecificationParameters, Get-SourceLocationForGallery, Get-StringHash...}
Script     0.0.0.1    PSGalleryDatabase                   PSGalleryDataBase

PS F:\psprivategallery\configuration> get-childitem "c:\program files\windowspowershell\modules\psgallery\dscresources"

    Directory: C:\program files\windowspowershell\modules\psgallery\dscresources

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         5/9/2017   3:08 PM                PSGalleryDatabase
d-----         5/9/2017   3:08 PM                PSGalleryDatabaseMigration
d-----         5/9/2017   3:08 PM                PSGalleryWebServer

The module is available and psgallerywebserver shows as a dscresource in the module.

**Comment by megamorf** [comment]
Please enclose your code in triple backticks to format it nicely. :-)

**Comment by GavinEke** [comment]
Same issue trying to set this up on Windows Server 2016, following the steps on the readme the step in question that is causing the issue is:

- Deploy the Gallery: ~\Configuration\PSPrivateGallery.ps1

```powershell
PS C:\PSPrivateGallery\Configuration> .\PSPrivateGallery.ps1


    Directory: C:\PSPrivateGallery\Configuration\LCMConfig


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       17/07/2017  11:52 AM           1294 localhost.meta.mof
VERBOSE: Performing the operation "Start-DscConfiguration: SendMetaConfigurationApply" on target
"MSFT_DSCLocalConfigurationManager".
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' =
SendMetaConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' =
root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer **retracted** with user sid
**retracted**.
VERBOSE: [**retracted**]: LCM:  [ Start  Set      ]
VERBOSE: [**retracted**]: LCM:  [ Start  Resource ]  [MSFT_DSCMetaConfiguration]
VERBOSE: [**retracted**]: LCM:  [ Start  Set      ]  [MSFT_DSCMetaConfiguration]
VERBOSE: [**retracted**]: LCM:  [ End    Set      ]  [MSFT_DSCMetaConfiguration]  in 0.0470 seconds.
VERBOSE: [**retracted**]: LCM:  [ End    Resource ]  [MSFT_DSCMetaConfiguration]
VERBOSE: [**retracted**]: LCM:  [ End    Set      ]
VERBOSE: [**retracted**]: LCM:  [ End    Set      ]    in  0.1880 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Set-DscLocalConfigurationManager finished in 0.416 seconds.
PSDesiredStateConfiguration\Node : The module 'PSGalleryWebServer' could not be loaded. For more information, run
'Import-Module PSGalleryWebServer'.
At C:\PSPrivateGallery\Configuration\PSPrivateGallery.ps1:20 char:5
+     Node $AllNodes.Where{$_.Role -eq 'WebServer'}.Nodename
+     ~~~~
    + CategoryInfo          : ObjectNotFound: (PSGalleryWebServer\PSGalleryWebServer:String) [PSDesiredStateConfigurat
   ion\node], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CouldNotAutoLoadModule,PSDesiredStateConfiguration\node

Compilation errors occurred while processing configuration 'PSPrivateGallery'. Please review the errors reported in
error stream and modify your configuration code appropriately.
At
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:3917
char:5
+     throw $ErrorRecord
+     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (PSPrivateGallery:String) [], InvalidOperationException
    + FullyQualifiedErrorId : FailToProcessConfiguration

PS C:\PSPrivateGallery\Configuration>
```
