### ISSUE TITLE
PSDesiredStateConfiguration\Node : Key not valid for use in specified state

### ISSUE THREAD

**Issue by sanjgaur** [PowerShell/PSPrivateGallery#37]
I get this error when trying to deploy using .\PSPrivateGallery.ps1 

After running c:\program Files \WindowsPowerShell\Modules\PSGallery\DSCResources\PSGalleryWebServer\PSGalleryWebserver.schema.psm1.

 Any help would be appreciated.

**Comment by pgemme** [comment]
Same error myself. I assumed it was permissions of that GalleryUser, so I created them locally but still get that error. Can I use different accounts for this part?
