### ISSUE TITLE
Download the binaries to a local folder instead of including them

### ISSUE THREAD

**Issue by Stijnc** [PowerShell/PSPrivateGallery#4]
I prefer to download the binaries located in the installer folder instead of including them in the project.
I would be happy to provide a pull request that uses the File and xRemoteFile resources.

**Comment by raghushantha** [comment]
As per #7, let us do this post [HQRM plan for xPSDesiredStateConfiguration](https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/dev/HighQualityResourceModulePlan.md)
