### ISSUE TITLE
Any idea when the project will end the PreviewMode?

### ISSUE THREAD

**Issue by kidchenko** [PowerShell/PSPrivateGallery#40]
We do not see a update in the source code more than 1 year. There is some plans to continue the development? Go out to preview mode?

**Comment by megamorf** [comment]
The main problem is that the original production code base has deviated a lot from the code you find on github. It's a shame but in its current state this repo is pretty much useless and you're better off trying to get a popular nuget repo like Nexus/Artifactory/etc. up and running :(
