### ISSUE TITLE
Include module version for 'external' dsc resources

### ISSUE THREAD

**Issue by Stijnc** [PowerShell/PSPrivateGallery#5]
A module version should be included for external dsc modules.
I have the the configuration failing on xWebadministration.
I would suggest adding a module version for:
- xWebAdministration
- PackageManagementProviderResource

I would be happy to provide a pull request

**Comment by raghushantha** [comment]
@Stijnc Please resubmit the PR - CLA is enabled for this repo now

**Comment by raghushantha** [comment]
https://github.com/PowerShell/PSPrivateGallery/commit/13075674e587f0c950893b61b63bb80e6be0cad8 takes care of adding the moduleversion
