### ISSUE TITLE
Run scripts on published modules and fail publishing depending on outcome

### ISSUE THREAD

**Issue by Tiberriver256** [PowerShell/PSPrivateGallery#8]
Would love it if we could configure PS scripts to be run on every script that was uploaded / published and publish or return an error based on the result of the script.

Some examples:
- Run psscriptanalyzer and refuse to publish if script does not meet threshold.
- Check for and run pester tests, refuse to publish if tests fail or are nonexistent.
- push to git repo on upload
- Sign scripts / modules with internal signature

**Comment by raghushantha** [comment]
@Tiberriver256 Good ideas..

We have a similar system for the public repository - PowerShellGallery.com where contents are ScriptAnalyzer scanned/tagged regularly.

In fact, ScriptAnalyzer has rules to validate the quality of a DSC resource (Tests present etc). It would be a good idea to run them and ensure the Check-in tests pass 100%

These must be DSC resources themselves - and integrated in Publish-Module pipeline
